// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Entry struct {
	ID     int64
	QuizID int64
	Name   string
}

type Quiz struct {
	ID   int64
	Name string
}

type Sorter struct {
	ID     int64
	Type   int64
	QuizID int64
	State  sql.NullString
}
