// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Entry struct {
	ID        int64
	QuizID    int64
	Name      string
	CreatedOn interface{}
	IsActive  bool
}

type Quiz struct {
	ID        int64
	Name      string
	UserID    int64
	CreatedOn interface{}
	IsActive  bool
}

type Session struct {
	Token  string
	UserID int64
	Expiry time.Time
}

type User struct {
	ID           int64
	Name         string
	PasswordHash string
	CreatedOn    interface{}
	IsActive     bool
}
